import React from 'react'

export default () => (
  <div style={{ textAlign: 'center' }}>
    <h1>Strawberry Sandwich</h1>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text Testing text </p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
    <p>Testing text</p>
  </div>
)
